openapi: 3.1.0
info:
  title: TrakNor API – Profile
  version: "1.0"
paths:
  /api/profile/:
    get:
      summary: Perfil do usuário autenticado
      tags: [Accounts]
      responses:
        "200":
          description: OK
components:
  schemas:
    UserRole:
      type: string
      enum: [admin, manager, technician]
