version: "3.9"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: traknor
      POSTGRES_USER: traknor
      POSTGRES_PASSWORD: traknor
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && gunicorn traknor.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DATABASE_URL: postgres://traknor:traknor@db:5432/traknor
      DJANGO_SETTINGS_MODULE: config.settings.prod
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /docs/openapi.yaml
    volumes:
      - ./backend/docs/openapi.yaml:/docs/openapi.yaml:ro
    ports:
      - "8080:8080"

volumes:
  pgdata:
