# Generated by Django 4.2.7 on 2025-06-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infra_accounts", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
